### ISSUE TITLE
Can only Drag Emote Menu Icon

### ISSUE THREAD

**Issue by arkham81a** [CBenni/mt2#57] opened 2018-04-22 11:56 UTC
Keep running into the same issue where the page is still fully functional, but I can't interact with it in any way aside from dragging borders and switching tabs. Clicking anywhere else will only drag the Emote Menu Icon around.

Video of the bug - https://streamable.com/8tmr9
Errors -  https://i.imgur.com/xpUPL7s.png
Config - https://pastebin.com/XnC7WuHh

**Comment by arkham81a** [comment] 2018-04-22 11:56
Granted this usually happens after I minimize/maximize the window a few times.

**Comment by CBenni** [comment] 2018-04-22 15:44
The errors have nothing to do with it, but thanks for the report; I cannot reproduce this but I will definitely try to figure out whats happening. If you find a way to do it consistently, please tell me!

**Comment by Kanthes** [comment] 2018-04-22 21:15
The div class "md-panel-outer-wrapper" ends up covering the entire screen, disabling any interactive elements such as the Emote menu, Chat text area, and other buttons. 

Focusing the interactive elements via developer tools shows the elements are still present and working, but cannot be accessed normally due to the div covering everything.

**Comment by CBenni** [comment] 2018-04-24 07:15
This is hopefully fixed now and in production, if this issue ever re-occurs, please reopen this issue.

**Closed by CBenni** 2018-04-24 07:15 UTC
Labels: bug
