### ISSUE TITLE
Chat ceases to send any message/mod command until refresh

### ISSUE THREAD

**Issue by LoLlYdE** [CBenni/mt2#121] opened 2018-06-23 15:46 UTC
This happens on staging directly after refreshing the page, console gives a `WebSocket is already in CLOSING or CLOSED state.` error when trying to send commands via inline mod icons or modcard commands, when trying the same command manually no console log appears, but nothing happens either. Sending normal chat messages doesnt work either, however other messages get recieved as expected.

Console log of the error:
![image](https://user-images.githubusercontent.com/11347524/41811158-98ed6026-770a-11e8-8b85-ffde138f7a08.png)

The relevant clicks/animations marked in red:
![image](https://user-images.githubusercontent.com/11347524/41811251-743c4c68-770c-11e8-90ac-01b2747def69.png)

Profile of the above screenshot: 
[Profile-20180623T174019.zip](https://github.com/CBenni/mt2/files/2130027/Profile-20180623T174019.zip)

note: the bottom stream had ended, thats why it looks like its loading. Sorry if this is a duplicate, I couldnt find an issue describing this exact error

**Comment by Civrock1** [comment] 2018-06-23 16:01
I've been meaning to report this same issue. I usually run into this after the modch.at window has been open for a while, incoming chat works just fine... however when I type something and submit, nothing appears in chat but text input is cleared. I checked Logviewer to make sure but nothing there for my username, confirming it never sent. Refresh page and it works fine.

**Comment by CBenni** [comment] 2018-09-07 23:29
Duplicate of #87

**Closed by CBenni** 2018-09-07 23:29 UTC
Labels: bug
